### ISSUE TITLE
висит после авторизации

### ISSUE THREAD

**Issue by wake0up0ne0** [s3rgeym/hh-applicant-tool#4]
А можно ли без арча, для тупеньких, как я?  

Пробовал 3 сорта LTS убунты, нигде не заводится, после authorize и синей кнопки выбора аккаунта ничего не происходит. 

Хэндлер зарегал. 
Не WSL.

```
Авторизуйтесь и нажмите <Подтвердить>
[I]  Запускаем TCP-сервер и слушаем unix:///tmp/hhandroid.sock
Gtk-Message: 18:56:10.541: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:56:10.543: Failed to load module "canberra-gtk-module"
```

**Comment by wake0up0ne0** [comment]
Звезда в репо и проклятье любителю шагов отгружены 🫶

**Comment by s3rgeym** [comment]
Значит не установлен socat
